import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../src/app/styles/globals.css';
import { getLocale, getMessages } from 'next-intl/server';
import { Analytics } from '@vercel/analytics/react';

import { IntlProvider, TelegramProvider } from '@/app/providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <IntlProvider messages={messages} locale={locale}>
          <TelegramProvider>{children}</TelegramProvider>
        </IntlProvider>
        <Analytics />
      </body>
    </html>
  );
}
