export const GAME_CONFIG = {
  // Цвета игры
  COLORS: ['#FF5733', '#33FF57', '#3357FF', '#F333FF', '#FFF333'],
  TARGET_COLOR_SPAWN_CHANCE: 0.3,
  MIN_CIRCLES_FOR_GUARANTEE: 5,

  // Жизни и время
  DEFAULT_LIVES: 3,
  TIME_TO_CHANGE_COLOR_MS: 10000,

  // Круги
  CIRCLE_RADIUS: 100,
  CIRCLE_RADIUS_VARIANCE: 0.5,
  CIRCLE_LIFETIME_MS: 5000,
  CIRCLE_LIFETIME_VARIANCE: 0.5,
  SPAWN_INTERVAL_MS: 500,
  MAX_CIRCLES_ON_SCREEN: 20,

  // Частицы
  PARTICLE_SIZE: 5,
  PARTICLE_LIFE_MS: 1000,
  MAX_PARTICLES: 50,

  // Эффект потери жизни
  LOSE_LIFE_FREEZE_MS: 750,
  LOSE_LIFE_HEART_MAX_SIZE: 500,
  LOSE_LIFE_HEART_DURATION_MS: 1000,
} as const;
